# ==============================================================
# = Autentication Server JWT
# ==============================================================

spring:
    application:
        name: AUTH-SERVICE

server:
    port: 9100

# ==============================================================
# = Parametri Servizio gestUser
# ==============================================================
gestuser:
  srvUrl: http://localhost:8019/api/utenti/cerca/userId/
  userId: Admin
  password: VerySecretPwd

# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 86400
    secret: 123_Stella

# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================  
logging:
  level:
    org.springframework.security: DEBUG


        

  
 